# Generated by Django 3.2.25 on 2024-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='link_url',
            field=models.CharField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=4000, unique=True),
        ),
    ]
