# Generated by Django 3.2.25 on 2024-07-12 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240702_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTreeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_tree_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyTreeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('vertical', 'parent'), ('horizontal', 'partner')], max_length=10)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='api.familytreemember')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_tree_relations', to=settings.AUTH_USER_MODEL)),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='api.familytreemember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='familytreemember',
            name='relations',
            field=models.ManyToManyField(related_name='related_to', through='api.FamilyTreeRelation', to='api.FamilyTreeMember'),
        ),
    ]
